Дерево поиска
ArtemNikit1n/homework-1st-semester pull request #16
Opened 2024-11-17 11:59 UTC by ArtemNikit1n

2024-12-30 21:19 UTC, yurii-litvinov requested changes
Чуть-чуть поправить бы надо. И применить все подходящие замечания, которые были к задаче про АВЛ

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +    *root = NULL;
Строго говоря, это имеет смысл только для корня всего дерева, так что я бы, как обычно, сделал нерекурсивную функцию-обёртку, которая бы присваивала NULL, а обычный deleteTree бы этого не делал. Но это совсем придирки :)

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.h
> +    char* value;
Тут возникает интересный вопрос про владение value. Как я понял из кода, вызывающий обязан выделить память на куче и передать её во владение дереву. Неудобно, лучше бы дерево само отвечало за выделение памяти.

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +    const char* foundValue = NULL;
Объявили бы на 112-й строчке

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +    }
Это не нужно, об этом строка 100 позаботится на следующем шаге рекурсии

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +        }
Что-то как-то извращённо, можно было сразу внутри if в 141 строке это делать

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +            Node* replacementNode = deleteNode(node, node->right->value.key, errorCode);
Так сразу правый сын удаляется? Там же хитрее процедура

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/SearchTree/main.c
> +    int c;
:(

2024-12-30 21:19 UTC, yurii-litvinov commented on 08-trees/Tree/main.c
> +#include <stdio.h>
Не уверен, что этот файл и четыре ниже нужны

2025-01-08 19:15 UTC, ArtemNikit1n commented on 08-trees/SearchTree/dictionary.c
> +            Node* replacementNode = deleteNode(node, node->right->value.key, errorCode);
А что за процедура? Почему нельзя всегда удаляемый элемент искать в правом поддереве? Левое и правое ничем же не отличаются

2025-01-12 08:50 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +            Node* replacementNode = deleteNode(node, node->right->value.key, errorCode);
Нет, меня смущает node->right->value.key, передаваемый в deleteNode. Удаляемый элемент, как я понимаю этот код, не ищется как самый маленький в правом поддереве, а просто полагается правым сыном, что неверно при, например, такой конфигурации
```
                 (удаляемый элемент)
                                  \
                               (правый сын)
                               /         \
          (настоящий узел на замену)   (правый внук)
```

2025-01-12 09:11 UTC, ArtemNikit1n commented on 08-trees/SearchTree/dictionary.c
> +            Node* replacementNode = deleteNode(node, node->right->value.key, errorCode);
Если я заменю на правого внука, то инвариант не должен нарушится, т к все узлы находящиеся в правом поддереве меньше самого узла. Почему нужно именно минимум правой части искать?

2025-01-15 12:16 UTC, yurii-litvinov requested changes
Ещё чуть-чуть бы поправить всё-таки

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +Node* createNode(NodeValue value, bool* errorCode) {
Эта функция вроде как нигде не используется

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +        free((*root)->value.value);
free хороша тем, что на NULL ничего не делает. Оно так специально, чтобы не надо было писать if

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +        node->value.value = value;
Тут, кажется, не хватает отчистки памяти, выделенной под старое node->value.value, и копирования value

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +}
А если ни один из if-ов выше не сработал? Математика говорит, что это невозможно, но компилятору сложновато сделать такой вывод, так что тут должен был выдать предупреждение

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +    }
Не поправлено

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/dictionary.c
> +    return foundValue;
```suggestion
    if (node->value.key < key) {
        return searchByKey(node->right, key);
    }
    return searchByKey(node->left, key);
```
Или даже так:
```c
    return node->value.key < key ? searchByKey(node->right, key) : searchByKey(node->left, key);
```
Или так:
```c
    return searchByKey(node->value.key < key ? node->right : node->left, key);
```

2025-01-15 12:16 UTC, yurii-litvinov commented on 08-trees/SearchTree/main.c
> +            free(value);
Можно было теперь getValueFromTheUser модифицировать, чтобы она принимала массив, куда надо сложить результат, и тогда можно было бы обойтись без аллокаций вовсе. Выделять память под value имеет смысл, если бы getValueFromTheUser читала бы строку произвольной длины, делая realloc — но она так не умеет

2025-02-15 18:43 UTC, merged