Дерево разбора
ArtemNikit1n/homework-1st-semester pull request #17
Opened 2024-11-20 09:34 UTC by ArtemNikit1n

2025-01-01 14:34 UTC, yurii-litvinov requested changes

2025-01-01 14:34 UTC, yurii-litvinov commented on 08-trees/SearchTree/SearchTree.vcxproj
>        <Configuration>Release</Configuration>
Тут какие-то ненужные изменения в SearchTree, их лучше откатить, чтобы в этом пуллреквесте были только изменения к дереву разбора

2025-01-01 14:34 UTC, yurii-litvinov commented on Dynamic data structures/Stack/main.c
> +﻿#include <stdio.h>
А чем этот стек отличается от того, что в 08-trees/Stack?

2025-01-01 14:34 UTC, yurii-litvinov commented on Dynamic data structures/fileForGit.txt
> +Файл нужен для существования пустой втеки
Не ветки, а папки, это другое совсем :)

2025-01-01 14:34 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/theParsingTree.c
> +        }
Так отрицательные числа не распарсятся

2025-01-01 14:34 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/theParsingTree.c
> +        return '\0';
Из xoid-функции ничего особо не вернёшь

2025-01-01 14:34 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/main.c
> +    return errorCode;
Надо память ещё очистить

2025-01-01 14:34 UTC, yurii-litvinov commented on 08-trees/Tree/testsForTree.c
> +        return false;
Что-то тут не все узлы удаляются

2025-01-01 18:38 UTC, ArtemNikit1n commented on 08-trees/TheParsingTree/theParsingTree.c
> +        }
Если изменить массив numbers (вот так: `const char numbers[] = "-0123456789";`), то отрицательные парсятся, но с учётом того, что, например, -6 и - 6 не одно и то же. Такое решение подойдёт?

2025-01-05 20:12 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/theParsingTree.c
> +        }
Да, вполне. Можно считать, что унарный минус никогда пробелом не отделяется.

2025-01-14 20:00 UTC, yurii-litvinov approved these changes
Ещё не идеально, но исправления тривиальны, так что зачтена

2025-01-14 20:00 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/testsForTheParsingTree.c
> +        return errorCode;
```suggestion
        *errorCode = true;
        return true;
```
А то тут беда с типизацией. Ну, и ниже.

2025-01-14 20:00 UTC, yurii-litvinov commented on 08-trees/TheParsingTree/theParsingTree.c
> +            return NULL;
Тут и ниже так дерево и стек утекут

2025-01-14 20:00 UTC, yurii-litvinov commented on 08-trees/Tree/main.c
> +void printNode(Node* node, bool* errorCode) {
Вроде как нигде не используется

2025-02-15 19:19 UTC, merged