АВЛ-дерево
ArtemNikit1n/homework-1st-semester pull request #18
Opened 2024-11-27 19:23 UTC by ArtemNikit1n

2024-12-29 11:07 UTC, yurii-litvinov requested changes
АВЛ-дерево вдвое короче пишется, какой-то оверинжиниринг получился (а иногда и просто раздувание объёма кода на ровном месте) :) Чем проще и короче — тем лучше, за строки кода давно уже никому зарплату не платят.

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +    root->value.value = value;
Так получается, что дерево берёт владение указателями, переданными извне, и обязано их удалить. Что делает невозможным, например, использование строковых литералов в духе `createTree("1", "2", errorCode);`, потому что их удалить не получится. Я бы тут strdup делал и оставлял владение указателем у вызывающего.

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +}
А тут Вы key и value не удаляете, потому что тесты падали, небось? :)

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.h
> +} NodeValue;
Ни одна функция интерфейса дерева не принимает эту структуру, следовательно она не нужна (в .h-нике точно, её буквально никак внешнему миру не использовать, даже если бы он захотел)

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +    return foundValue;
```suggestion
    if (strcmp(node->value.key, key) < 0) {
        return searchByKey(node->right, key);
    }
    return searchByKey(node->left, key);
```
И тогда foundValue будет вообще не нужно

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +        }
Кажется, есть более простой способ пересчёта баланса, но если так работает, то и ладно

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +        node->value.value = value;
Не-а, надо сначала старый value удалить

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +        else {
else тут не нужен, ветка then заканчивается return-ом

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            }
```suggestion
            *isHeightChanged = node->balance != 0;
            return node;
```

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            free(node->right);
- Удаляем узел, но не его содержимое?
- Я бы удаление делал в районе 273 строчки, иначе тут какой-то суперсложный код без нужды получается

2024-12-29 11:07 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/main.c
> +void callTheFunction(int functionCode, bool* errorCode) {
Название функции не очень

2024-12-30 21:53 UTC, ArtemNikit1n commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            free(node->right);
Если я сделаю удаление на 273, то когда я вернусь из рекурсии вместо узла будет мусор. Я могу как-то отличить мусор в памяти от нормального значения? Или как можно удалить так, чтобы указатель (в данном случае `node->right`) был равен NULL?

2025-01-05 20:11 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            free(node->right);
Отличить мусор от не мусора просто по содержимому ячейки памяти нельзя, просто потому, что после free содержимое памяти имеет полное право вовсе не меняться (она просто добавляется в список свободных блоков, поддерживаемый менеджером памяти ОС). А вот занулить указатель можно. Обычно делают что-то вроде `node->right = deleteNode(node->right, ...);`, и когда deleteNode возвращает NULL, он спокойно записывается куда надо (а если не NULL, то новое правое поддерево вешается как правый сын). Альтернативный подход — deleteNode(&(node->right), ...);` и внутри функции `*node = NULL;`.

2025-01-05 20:32 UTC, ArtemNikit1n commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            free(node->right);
Да, я могу занулить, но я никак не смогу сообщить родителю о том, что его сын теперь NULL без указателя на родителя. Поэтому, когда я вернусь из рекурсии сын не будет NULL, там будет просто мусор. Именно по этой причине я удалял на моменте когда вернулся на один шаг из рекурсии. Можно ли как-то реализовать ваше решение без указателей на родителя?

2025-01-05 20:41 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +            free(node->right);
Так я буквально написал два способа это сделать в комменте выше :) Либо когда вернётесь из рекурсии присваиваете сыну то значение, что рекурсия вернула, либо передаёте сына по двойному указателю и зануляете его, таким образом он зануляется и у родителя

2025-01-14 16:11 UTC, yurii-litvinov approved these changes
Не берусь поручиться, что в этой ужасной функции удаления всё правильно, но раз тесты проходит, то и ладно. Зачтена.

2025-01-14 16:11 UTC, yurii-litvinov commented on 09-self-balancing-trees/AVL-tree/avlTree.c
> +        free(node->value.value);
Можно было сначала strdup и проверку, затем free, чтобы если всё плохо, дерево не модифицировалось

2025-02-10 11:14 UTC, merged