Государства
ArtemNikit1n/homework-1st-semester pull request #23
Opened 2024-12-23 10:28 UTC by ArtemNikit1n

2024-12-28 16:01 UTC, yurii-litvinov requested changes
В целом всё так, но технические огрехи стоит исправить

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/Dynamic data structures/Stack/stack.c
> +    Stack* stack = *stackDoublePointer;
Вот это, кстати, хорошая идея, чтобы код внутри функции выглядел менее агрессивно. Только параметр функции надо называть"красиво", не указывать в имени тип точно.

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +    int numberVertices;
numberOfVertices лучше, чтобы как выше

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +    int** adjacencyMatrix;
Есть и матрица смежности, и список смежности в каждой вершине, что-то из них избыточно

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +    matrix = realloc(matrix, desiredSize * sizeof(int*));
Надо делать realloc во временную переменную сначала, чтобы иметь возможность удалить старую матрицу. Так мы на неё указатель потеряем

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +            return;
А тут надо решить, что делать с уже выделенной памятью. Думаю, что аккуратно удалить всё и вернуть NULL

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +        return;
return что? :)

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +            }
Технически, это тоже можно делать через memset, он хочет указатель не на начало массива, а на начало памяти, которую надо забить нулями

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +        graph->vertices = realloc(graph->vertices, (value.key + 1) * sizeof(Vertex*));
Тут тоже проблема с тем, что realloc в случае неудачи вернёт NULL и старую область памяти не тронет

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +            return;
Ну и тут. Проверьте везде, что даже в случае ошибки всё корректно деаллоцируется, закроется и удалится

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +        vertex->adjacentVertices = realloc(vertex->adjacentVertices, (vertex->numberOfAdjacentVertices + 1) * sizeof(Vertex*));
Сделали бы списки на указателях или честный АТД "Массив изменяющейся длины" наподобие std::vector в C++ :) Постоянные realloc на 1 — очень нетехнологично. Это можно не переделывать, если что

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +void addNearestCity(Graph* graph, const int city, bool* errorCode) {
Параметр называется city, а играет роль номера государства, путает

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +        enqueue(capitals, selectedCity, errorCode);
Правда нужна очередь, чтобы просто последовательно перебирать номера столиц? Можно было просто бежать по graph->vertices[i], останавливаясь на тех, доя кого истинно graph->vertices[i]->value.isCapital, и если i == graph->numberVertices, то i присваивать 0. Так, конечно, тоже будет работать, но это как стрельба из пушки по воробьям. Удивляет читателя, а хороший код не должен удивлять. Если очередь нигде больше не нужна, стоит это убрать, и очередь тоже (что сократит объём кода, что всегда хорошо). Если нужна, то можно оставить.

2024-12-28 16:01 UTC, yurii-litvinov commented on 11-graphs/States/main.c
> +    }
```suggestion
    testGraph(&errorCode);
    testQueue(&errorCode);
    if (errorCode) {
        return errorCode;
    }
```
Тесты ведь независимы друг от друга, если хоть один не пройдёт, то всё, но почему бы им обоим не дать поработать

2024-12-28 19:21 UTC, ArtemNikit1n commented on 11-graphs/Dynamic data structures/Stack/stack.c
> +    Stack* stack = *stackDoublePointer;
А что плохого в том, что переменная называется как тип? Тут, конечно, криво написано, но почему нельзя `pointerToStack`? Разве пользователю не будет удобнее, если называние переменной будет подсказывать, что нужно передать в функцию?

2024-12-28 21:37 UTC, ArtemNikit1n commented on 11-graphs/States/main.c
> +    }
Но если мы хотим, чтобы очередь тоже тестировалась, разве не нужно сбросить код ошибки? И как понять тогда прошли ли тесты для графов? Получается нужно результаты тестов в отдельных переменных хранить? Кстати, графы использую очередь, можно сказать, что если тесты для очереди не проходят, то графы можно не проверять?

2024-12-29 09:44 UTC, yurii-litvinov commented on 11-graphs/Dynamic data structures/Stack/stack.c
> +    Stack* stack = *stackDoublePointer;
Пользователь это и так знает, ему IDEшка подсказывает. Почему плохо: потому что название типа — это техническая вещь, а имя переменной должно отражать её смысл в предметной области. Программа в идеале должна читаться будто это текст на естественном языке, даже экспертом предметной области, не владеющим языком программирования (да, Си для этого слабо подходит, но мы стараемся по максимуму к этому приблизиться, более современные языки в этом плане лучше). Погуглите "Венгерская нотация" ещё, кстати. В частности, мнение Линуса Торвальдса про эту идею.

2024-12-29 09:49 UTC, yurii-litvinov commented on 11-graphs/States/main.c
> +    }
А мне казалось, что у Вас намеренно нигде errorCode не выставляется в true, чтобы если он единожды стал false, он оставался false. И тесты на errorCode не смотрят, они просто выставляют его в false, если что-то пошло не так. Если это неправда, то, может, стоит так сделать.

В реальной жизни общая политика такая, что запускаем все тесты, какие можем, потом разбираемся (правда, в реальной жизни использовались бы mock-объекты, чтобы разорвать связь между графом и очередью). Это хотя бы даст шанс за один тестовый прогон выявить ошибки в графе (может, он падает, не дойдя до очередей). Почему — тестов обычно много и гоняются они долго, так что чтобы поправить ошибку и перезапустить, может потребоваться следующего дня ждать.

2024-12-29 19:52 UTC, ArtemNikit1n commented on 11-graphs/States/main.c
> +    }
errorCode выставляется в true в случае какой-либо ошибки. Я думал, если что-то пошло не так, нужно выставить true и завершить программу, почему тесты должны выставлять его в false, если что-то не так?

2024-12-30 20:27 UTC, yurii-litvinov commented on 11-graphs/States/main.c
> +    }
Значит, в рассуждении выше наоборот, true -> false. Если произошла какая-то ошибка, errorCode оказывается в состоянии "ошибка" и никак не может из него выйти (что хорошо и правильно), поэтому мы смело можем запускать все остальные тесты, ошибка не потеряется.

2024-12-30 20:32 UTC, yurii-litvinov approved these changes
Да, окей. Зачтена

2024-12-30 20:32 UTC, yurii-litvinov commented on 11-graphs/States/graph.c
> +        }
Это просто странно записанный while (true) или while (graph->numberOfCitiesOutsideState > 0)

2025-02-10 11:13 UTC, merged